"""Add Freebie

Revision ID: 0a1bfa536eec
Revises: b96a7f18344f
Create Date: 2023-09-06 17:00:18.909256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a1bfa536eec'
down_revision = 'b96a7f18344f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
